version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: e_uprava
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5437:5432" # external 5437 â†’ internal 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  e-goverment:
    build: ./e-goverment
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e_uprava
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  traffic-police-service:
    build: ./traffic-police-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e_uprava
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  mup-vehicles:
    build: ./mup-vehicles
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e_uprava
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
